Repository PIYUSH-69/SCANNER-APP, pull requests merged in 2023-10, with the labels that each got.

#5 Made links clickable and added clipboard functionality & formatted code
  app/src/main/java/com/example/scanme/MainActivity2.kt
  app/src/main/res/drawable/baseline_content_copy_24.xml
  app/src/main/res/layout/activity_main2.xml
Labels: hacktoberfest

#7 DONE
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/font/actor.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main2.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#8 DONE
  README.md
  Screenshots/Screenshot_20231028_185700.png
  Screenshots/Screenshot_20231028_185726.png
Labels: hacktoberfest, hacktoberfest-accepted
